QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++11

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    finddock.cpp \
    hunspell/src/hunspell/affentry.cxx \
    hunspell/src/hunspell/affixmgr.cxx \
    hunspell/src/hunspell/csutil.cxx \
    hunspell/src/hunspell/filemgr.cxx \
    hunspell/src/hunspell/hashmgr.cxx \
    hunspell/src/hunspell/hunspell.cxx \
    hunspell/src/hunspell/hunzip.cxx \
    hunspell/src/hunspell/phonet.cxx \
    hunspell/src/hunspell/replist.cxx \
    hunspell/src/hunspell/suggestmgr.cxx \
    main.cpp \
    mainwindow.cpp \
    mdhighlighter.cpp \
    settingsdock.cpp \
    spellchecker.cpp \
    texteditor.cpp

HEADERS += \
    finddock.h \
    hunspell/src/hunspell/affentry.hxx \
    hunspell/src/hunspell/affixmgr.hxx \
    hunspell/src/hunspell/atypes.hxx \
    hunspell/src/hunspell/baseaffix.hxx \
    hunspell/src/hunspell/csutil.hxx \
    hunspell/src/hunspell/filemgr.hxx \
    hunspell/src/hunspell/hashmgr.hxx \
    hunspell/src/hunspell/htypes.hxx \
    hunspell/src/hunspell/hunspell.h \
    hunspell/src/hunspell/hunspell.hxx \
    hunspell/src/hunspell/hunvisapi.h \
    hunspell/src/hunspell/hunvisapi.h.in \
    hunspell/src/hunspell/hunzip.hxx \
    hunspell/src/hunspell/langnum.hxx \
    hunspell/src/hunspell/phonet.hxx \
    hunspell/src/hunspell/replist.hxx \
    hunspell/src/hunspell/suggestmgr.hxx \
    hunspell/src/hunspell/utf_info.hxx \
    hunspell/src/hunspell/w_char.hxx \
    mainwindow.h \
    mdhighlighter.h \
    settingsdock.h \
    spellchecker.h \
    texteditor.h

TRANSLATIONS += \
    Editor_de_DE.ts \
    Editor_en_EN.ts

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

FORMS +=

DISTFILES += \
    Editor_de_DE.qm \
    Editor_en_EN.qm \
    Icon.png \
    dark_style.qss \
    dictionaries/dictionaries/bg/index.aff \
    dictionaries/dictionaries/bg/index.dic \
    dictionaries/dictionaries/bg/index.js \
    dictionaries/dictionaries/bg/license \
    dictionaries/dictionaries/bg/package.json \
    dictionaries/dictionaries/bg/readme.md \
    dictionaries/dictionaries/br/index.aff \
    dictionaries/dictionaries/br/index.dic \
    dictionaries/dictionaries/br/index.js \
    dictionaries/dictionaries/br/license \
    dictionaries/dictionaries/br/package.json \
    dictionaries/dictionaries/br/readme.md \
    dictionaries/dictionaries/ca-valencia/index.aff \
    dictionaries/dictionaries/ca-valencia/index.dic \
    dictionaries/dictionaries/ca-valencia/index.js \
    dictionaries/dictionaries/ca-valencia/license \
    dictionaries/dictionaries/ca-valencia/package.json \
    dictionaries/dictionaries/ca-valencia/readme.md \
    dictionaries/dictionaries/ca/index.aff \
    dictionaries/dictionaries/ca/index.dic \
    dictionaries/dictionaries/ca/index.js \
    dictionaries/dictionaries/ca/license \
    dictionaries/dictionaries/ca/package.json \
    dictionaries/dictionaries/ca/readme.md \
    dictionaries/dictionaries/cs/index.aff \
    dictionaries/dictionaries/cs/index.dic \
    dictionaries/dictionaries/cs/index.js \
    dictionaries/dictionaries/cs/license \
    dictionaries/dictionaries/cs/package.json \
    dictionaries/dictionaries/cs/readme.md \
    dictionaries/dictionaries/da/index.aff \
    dictionaries/dictionaries/da/index.dic \
    dictionaries/dictionaries/da/index.js \
    dictionaries/dictionaries/da/license \
    dictionaries/dictionaries/da/package.json \
    dictionaries/dictionaries/da/readme.md \
    dictionaries/dictionaries/de-AT/index.aff \
    dictionaries/dictionaries/de-AT/index.dic \
    dictionaries/dictionaries/de-AT/index.js \
    dictionaries/dictionaries/de-AT/license \
    dictionaries/dictionaries/de-AT/package.json \
    dictionaries/dictionaries/de-AT/readme.md \
    dictionaries/dictionaries/de-CH/index.aff \
    dictionaries/dictionaries/de-CH/index.dic \
    dictionaries/dictionaries/de-CH/index.js \
    dictionaries/dictionaries/de-CH/license \
    dictionaries/dictionaries/de-CH/package.json \
    dictionaries/dictionaries/de-CH/readme.md \
    dictionaries/dictionaries/de/index.aff \
    dictionaries/dictionaries/de/index.dic \
    dictionaries/dictionaries/de/index.js \
    dictionaries/dictionaries/de/license \
    dictionaries/dictionaries/de/package.json \
    dictionaries/dictionaries/de/readme.md \
    dictionaries/dictionaries/el-polyton/index.aff \
    dictionaries/dictionaries/el-polyton/index.dic \
    dictionaries/dictionaries/el-polyton/index.js \
    dictionaries/dictionaries/el-polyton/license \
    dictionaries/dictionaries/el-polyton/package.json \
    dictionaries/dictionaries/el-polyton/readme.md \
    dictionaries/dictionaries/el/index.aff \
    dictionaries/dictionaries/el/index.dic \
    dictionaries/dictionaries/el/index.js \
    dictionaries/dictionaries/el/license \
    dictionaries/dictionaries/el/package.json \
    dictionaries/dictionaries/el/readme.md \
    dictionaries/dictionaries/en-AU/index.aff \
    dictionaries/dictionaries/en-AU/index.dic \
    dictionaries/dictionaries/en-AU/index.js \
    dictionaries/dictionaries/en-AU/license \
    dictionaries/dictionaries/en-AU/package.json \
    dictionaries/dictionaries/en-AU/readme.md \
    dictionaries/dictionaries/en-CA/index.aff \
    dictionaries/dictionaries/en-CA/index.dic \
    dictionaries/dictionaries/en-CA/index.js \
    dictionaries/dictionaries/en-CA/license \
    dictionaries/dictionaries/en-CA/package.json \
    dictionaries/dictionaries/en-CA/readme.md \
    dictionaries/dictionaries/en-GB/index.aff \
    dictionaries/dictionaries/en-GB/index.dic \
    dictionaries/dictionaries/en-GB/index.js \
    dictionaries/dictionaries/en-GB/license \
    dictionaries/dictionaries/en-GB/package.json \
    dictionaries/dictionaries/en-GB/readme.md \
    dictionaries/dictionaries/en-ZA/index.aff \
    dictionaries/dictionaries/en-ZA/index.dic \
    dictionaries/dictionaries/en-ZA/index.js \
    dictionaries/dictionaries/en-ZA/license \
    dictionaries/dictionaries/en-ZA/package.json \
    dictionaries/dictionaries/en-ZA/readme.md \
    dictionaries/dictionaries/en/index.aff \
    dictionaries/dictionaries/en/index.dic \
    dictionaries/dictionaries/en/index.js \
    dictionaries/dictionaries/en/license \
    dictionaries/dictionaries/en/package.json \
    dictionaries/dictionaries/en/readme.md \
    dictionaries/dictionaries/eo/index.aff \
    dictionaries/dictionaries/eo/index.dic \
    dictionaries/dictionaries/eo/index.js \
    dictionaries/dictionaries/eo/license \
    dictionaries/dictionaries/eo/package.json \
    dictionaries/dictionaries/eo/readme.md \
    dictionaries/dictionaries/es-AR/index.aff \
    dictionaries/dictionaries/es-AR/index.dic \
    dictionaries/dictionaries/es-AR/index.js \
    dictionaries/dictionaries/es-AR/license \
    dictionaries/dictionaries/es-AR/package.json \
    dictionaries/dictionaries/es-AR/readme.md \
    dictionaries/dictionaries/es-BO/index.aff \
    dictionaries/dictionaries/es-BO/index.dic \
    dictionaries/dictionaries/es-BO/index.js \
    dictionaries/dictionaries/es-BO/license \
    dictionaries/dictionaries/es-BO/package.json \
    dictionaries/dictionaries/es-BO/readme.md \
    dictionaries/dictionaries/es-CL/index.aff \
    dictionaries/dictionaries/es-CL/index.dic \
    dictionaries/dictionaries/es-CL/index.js \
    dictionaries/dictionaries/es-CL/license \
    dictionaries/dictionaries/es-CL/package.json \
    dictionaries/dictionaries/es-CL/readme.md \
    dictionaries/dictionaries/es-CO/index.aff \
    dictionaries/dictionaries/es-CO/index.dic \
    dictionaries/dictionaries/es-CO/index.js \
    dictionaries/dictionaries/es-CO/license \
    dictionaries/dictionaries/es-CO/package.json \
    dictionaries/dictionaries/es-CO/readme.md \
    dictionaries/dictionaries/es-CR/index.aff \
    dictionaries/dictionaries/es-CR/index.dic \
    dictionaries/dictionaries/es-CR/index.js \
    dictionaries/dictionaries/es-CR/license \
    dictionaries/dictionaries/es-CR/package.json \
    dictionaries/dictionaries/es-CR/readme.md \
    dictionaries/dictionaries/es-CU/index.aff \
    dictionaries/dictionaries/es-CU/index.dic \
    dictionaries/dictionaries/es-CU/index.js \
    dictionaries/dictionaries/es-CU/license \
    dictionaries/dictionaries/es-CU/package.json \
    dictionaries/dictionaries/es-CU/readme.md \
    dictionaries/dictionaries/es-DO/index.aff \
    dictionaries/dictionaries/es-DO/index.dic \
    dictionaries/dictionaries/es-DO/index.js \
    dictionaries/dictionaries/es-DO/license \
    dictionaries/dictionaries/es-DO/package.json \
    dictionaries/dictionaries/es-DO/readme.md \
    dictionaries/dictionaries/es-EC/index.aff \
    dictionaries/dictionaries/es-EC/index.dic \
    dictionaries/dictionaries/es-EC/index.js \
    dictionaries/dictionaries/es-EC/license \
    dictionaries/dictionaries/es-EC/package.json \
    dictionaries/dictionaries/es-EC/readme.md \
    dictionaries/dictionaries/es-GT/index.aff \
    dictionaries/dictionaries/es-GT/index.dic \
    dictionaries/dictionaries/es-GT/index.js \
    dictionaries/dictionaries/es-GT/license \
    dictionaries/dictionaries/es-GT/package.json \
    dictionaries/dictionaries/es-GT/readme.md \
    dictionaries/dictionaries/es-HN/index.aff \
    dictionaries/dictionaries/es-HN/index.dic \
    dictionaries/dictionaries/es-HN/index.js \
    dictionaries/dictionaries/es-HN/license \
    dictionaries/dictionaries/es-HN/package.json \
    dictionaries/dictionaries/es-HN/readme.md \
    dictionaries/dictionaries/es-MX/index.aff \
    dictionaries/dictionaries/es-MX/index.dic \
    dictionaries/dictionaries/es-MX/index.js \
    dictionaries/dictionaries/es-MX/license \
    dictionaries/dictionaries/es-MX/package.json \
    dictionaries/dictionaries/es-MX/readme.md \
    dictionaries/dictionaries/es-NI/index.aff \
    dictionaries/dictionaries/es-NI/index.dic \
    dictionaries/dictionaries/es-NI/index.js \
    dictionaries/dictionaries/es-NI/license \
    dictionaries/dictionaries/es-NI/package.json \
    dictionaries/dictionaries/es-NI/readme.md \
    dictionaries/dictionaries/es-PA/index.aff \
    dictionaries/dictionaries/es-PA/index.dic \
    dictionaries/dictionaries/es-PA/index.js \
    dictionaries/dictionaries/es-PA/license \
    dictionaries/dictionaries/es-PA/package.json \
    dictionaries/dictionaries/es-PA/readme.md \
    dictionaries/dictionaries/es-PE/index.aff \
    dictionaries/dictionaries/es-PE/index.dic \
    dictionaries/dictionaries/es-PE/index.js \
    dictionaries/dictionaries/es-PE/license \
    dictionaries/dictionaries/es-PE/package.json \
    dictionaries/dictionaries/es-PE/readme.md \
    dictionaries/dictionaries/es-PH/index.aff \
    dictionaries/dictionaries/es-PH/index.dic \
    dictionaries/dictionaries/es-PH/index.js \
    dictionaries/dictionaries/es-PH/license \
    dictionaries/dictionaries/es-PH/package.json \
    dictionaries/dictionaries/es-PH/readme.md \
    dictionaries/dictionaries/es-PR/index.aff \
    dictionaries/dictionaries/es-PR/index.dic \
    dictionaries/dictionaries/es-PR/index.js \
    dictionaries/dictionaries/es-PR/license \
    dictionaries/dictionaries/es-PR/package.json \
    dictionaries/dictionaries/es-PR/readme.md \
    dictionaries/dictionaries/es-PY/index.aff \
    dictionaries/dictionaries/es-PY/index.dic \
    dictionaries/dictionaries/es-PY/index.js \
    dictionaries/dictionaries/es-PY/license \
    dictionaries/dictionaries/es-PY/package.json \
    dictionaries/dictionaries/es-PY/readme.md \
    dictionaries/dictionaries/es-SV/index.aff \
    dictionaries/dictionaries/es-SV/index.dic \
    dictionaries/dictionaries/es-SV/index.js \
    dictionaries/dictionaries/es-SV/license \
    dictionaries/dictionaries/es-SV/package.json \
    dictionaries/dictionaries/es-SV/readme.md \
    dictionaries/dictionaries/es-US/index.aff \
    dictionaries/dictionaries/es-US/index.dic \
    dictionaries/dictionaries/es-US/index.js \
    dictionaries/dictionaries/es-US/license \
    dictionaries/dictionaries/es-US/package.json \
    dictionaries/dictionaries/es-US/readme.md \
    dictionaries/dictionaries/es-UY/index.aff \
    dictionaries/dictionaries/es-UY/index.dic \
    dictionaries/dictionaries/es-UY/index.js \
    dictionaries/dictionaries/es-UY/license \
    dictionaries/dictionaries/es-UY/package.json \
    dictionaries/dictionaries/es-UY/readme.md \
    dictionaries/dictionaries/es-VE/index.aff \
    dictionaries/dictionaries/es-VE/index.dic \
    dictionaries/dictionaries/es-VE/index.js \
    dictionaries/dictionaries/es-VE/license \
    dictionaries/dictionaries/es-VE/package.json \
    dictionaries/dictionaries/es-VE/readme.md \
    dictionaries/dictionaries/es/index.aff \
    dictionaries/dictionaries/es/index.dic \
    dictionaries/dictionaries/es/index.js \
    dictionaries/dictionaries/es/license \
    dictionaries/dictionaries/es/package.json \
    dictionaries/dictionaries/es/readme.md \
    dictionaries/dictionaries/et/index.aff \
    dictionaries/dictionaries/et/index.dic \
    dictionaries/dictionaries/et/index.js \
    dictionaries/dictionaries/et/package.json \
    dictionaries/dictionaries/et/readme.md \
    dictionaries/dictionaries/eu/index.aff \
    dictionaries/dictionaries/eu/index.dic \
    dictionaries/dictionaries/eu/index.js \
    dictionaries/dictionaries/eu/package.json \
    dictionaries/dictionaries/eu/readme.md \
    dictionaries/dictionaries/fa/index.aff \
    dictionaries/dictionaries/fa/index.dic \
    dictionaries/dictionaries/fa/index.js \
    dictionaries/dictionaries/fa/license \
    dictionaries/dictionaries/fa/package.json \
    dictionaries/dictionaries/fa/readme.md \
    dictionaries/dictionaries/fo/index.aff \
    dictionaries/dictionaries/fo/index.dic \
    dictionaries/dictionaries/fo/index.js \
    dictionaries/dictionaries/fo/license \
    dictionaries/dictionaries/fo/package.json \
    dictionaries/dictionaries/fo/readme.md \
    dictionaries/dictionaries/fr/index.aff \
    dictionaries/dictionaries/fr/index.dic \
    dictionaries/dictionaries/fr/index.js \
    dictionaries/dictionaries/fr/license \
    dictionaries/dictionaries/fr/package.json \
    dictionaries/dictionaries/fr/readme.md \
    dictionaries/dictionaries/fur/index.aff \
    dictionaries/dictionaries/fur/index.dic \
    dictionaries/dictionaries/fur/index.js \
    dictionaries/dictionaries/fur/license \
    dictionaries/dictionaries/fur/package.json \
    dictionaries/dictionaries/fur/readme.md \
    dictionaries/dictionaries/fy/index.aff \
    dictionaries/dictionaries/fy/index.dic \
    dictionaries/dictionaries/fy/index.js \
    dictionaries/dictionaries/fy/license \
    dictionaries/dictionaries/fy/package.json \
    dictionaries/dictionaries/fy/readme.md \
    dictionaries/dictionaries/ga/index.aff \
    dictionaries/dictionaries/ga/index.dic \
    dictionaries/dictionaries/ga/index.js \
    dictionaries/dictionaries/ga/license \
    dictionaries/dictionaries/ga/package.json \
    dictionaries/dictionaries/ga/readme.md \
    dictionaries/dictionaries/gd/index.aff \
    dictionaries/dictionaries/gd/index.dic \
    dictionaries/dictionaries/gd/index.js \
    dictionaries/dictionaries/gd/license \
    dictionaries/dictionaries/gd/package.json \
    dictionaries/dictionaries/gd/readme.md \
    dictionaries/dictionaries/gl/index.aff \
    dictionaries/dictionaries/gl/index.dic \
    dictionaries/dictionaries/gl/index.js \
    dictionaries/dictionaries/gl/license \
    dictionaries/dictionaries/gl/package.json \
    dictionaries/dictionaries/gl/readme.md \
    dictionaries/dictionaries/he/index.aff \
    dictionaries/dictionaries/he/index.dic \
    dictionaries/dictionaries/he/index.js \
    dictionaries/dictionaries/he/license \
    dictionaries/dictionaries/he/package.json \
    dictionaries/dictionaries/he/readme.md \
    dictionaries/dictionaries/hr/index.aff \
    dictionaries/dictionaries/hr/index.dic \
    dictionaries/dictionaries/hr/index.js \
    dictionaries/dictionaries/hr/license \
    dictionaries/dictionaries/hr/package.json \
    dictionaries/dictionaries/hr/readme.md \
    dictionaries/dictionaries/hu/index.aff \
    dictionaries/dictionaries/hu/index.dic \
    dictionaries/dictionaries/hu/index.js \
    dictionaries/dictionaries/hu/license \
    dictionaries/dictionaries/hu/package.json \
    dictionaries/dictionaries/hu/readme.md \
    dictionaries/dictionaries/hy/index.aff \
    dictionaries/dictionaries/hy/index.dic \
    dictionaries/dictionaries/hy/index.js \
    dictionaries/dictionaries/hy/license \
    dictionaries/dictionaries/hy/package.json \
    dictionaries/dictionaries/hy/readme.md \
    dictionaries/dictionaries/hyw/index.aff \
    dictionaries/dictionaries/hyw/index.dic \
    dictionaries/dictionaries/hyw/index.js \
    dictionaries/dictionaries/hyw/license \
    dictionaries/dictionaries/hyw/package.json \
    dictionaries/dictionaries/hyw/readme.md \
    dictionaries/dictionaries/ia/index.aff \
    dictionaries/dictionaries/ia/index.dic \
    dictionaries/dictionaries/ia/index.js \
    dictionaries/dictionaries/ia/license \
    dictionaries/dictionaries/ia/package.json \
    dictionaries/dictionaries/ia/readme.md \
    dictionaries/dictionaries/ie/index.aff \
    dictionaries/dictionaries/ie/index.dic \
    dictionaries/dictionaries/ie/index.js \
    dictionaries/dictionaries/ie/license \
    dictionaries/dictionaries/ie/package.json \
    dictionaries/dictionaries/ie/readme.md \
    dictionaries/dictionaries/is/index.aff \
    dictionaries/dictionaries/is/index.dic \
    dictionaries/dictionaries/is/index.js \
    dictionaries/dictionaries/is/license \
    dictionaries/dictionaries/is/package.json \
    dictionaries/dictionaries/is/readme.md \
    dictionaries/dictionaries/it/index.aff \
    dictionaries/dictionaries/it/index.dic \
    dictionaries/dictionaries/it/index.js \
    dictionaries/dictionaries/it/license \
    dictionaries/dictionaries/it/package.json \
    dictionaries/dictionaries/it/readme.md \
    dictionaries/dictionaries/ka/index.aff \
    dictionaries/dictionaries/ka/index.dic \
    dictionaries/dictionaries/ka/index.js \
    dictionaries/dictionaries/ka/license \
    dictionaries/dictionaries/ka/package.json \
    dictionaries/dictionaries/ka/readme.md \
    dictionaries/dictionaries/ko/index.aff \
    dictionaries/dictionaries/ko/index.dic \
    dictionaries/dictionaries/ko/index.js \
    dictionaries/dictionaries/ko/license \
    dictionaries/dictionaries/ko/package.json \
    dictionaries/dictionaries/ko/readme.md \
    dictionaries/dictionaries/la/index.aff \
    dictionaries/dictionaries/la/index.dic \
    dictionaries/dictionaries/la/index.js \
    dictionaries/dictionaries/la/license \
    dictionaries/dictionaries/la/package.json \
    dictionaries/dictionaries/la/readme.md \
    dictionaries/dictionaries/lb/index.aff \
    dictionaries/dictionaries/lb/index.dic \
    dictionaries/dictionaries/lb/index.js \
    dictionaries/dictionaries/lb/license \
    dictionaries/dictionaries/lb/package.json \
    dictionaries/dictionaries/lb/readme.md \
    dictionaries/dictionaries/lt/index.aff \
    dictionaries/dictionaries/lt/index.dic \
    dictionaries/dictionaries/lt/index.js \
    dictionaries/dictionaries/lt/license \
    dictionaries/dictionaries/lt/package.json \
    dictionaries/dictionaries/lt/readme.md \
    dictionaries/dictionaries/ltg/index.aff \
    dictionaries/dictionaries/ltg/index.dic \
    dictionaries/dictionaries/ltg/index.js \
    dictionaries/dictionaries/ltg/license \
    dictionaries/dictionaries/ltg/package.json \
    dictionaries/dictionaries/ltg/readme.md \
    dictionaries/dictionaries/lv/index.aff \
    dictionaries/dictionaries/lv/index.dic \
    dictionaries/dictionaries/lv/index.js \
    dictionaries/dictionaries/lv/license \
    dictionaries/dictionaries/lv/package.json \
    dictionaries/dictionaries/lv/readme.md \
    dictionaries/dictionaries/mk/index.aff \
    dictionaries/dictionaries/mk/index.dic \
    dictionaries/dictionaries/mk/index.js \
    dictionaries/dictionaries/mk/license \
    dictionaries/dictionaries/mk/package.json \
    dictionaries/dictionaries/mk/readme.md \
    dictionaries/dictionaries/mn/index.aff \
    dictionaries/dictionaries/mn/index.dic \
    dictionaries/dictionaries/mn/index.js \
    dictionaries/dictionaries/mn/license \
    dictionaries/dictionaries/mn/package.json \
    dictionaries/dictionaries/mn/readme.md \
    dictionaries/dictionaries/nb/index.aff \
    dictionaries/dictionaries/nb/index.dic \
    dictionaries/dictionaries/nb/index.js \
    dictionaries/dictionaries/nb/license \
    dictionaries/dictionaries/nb/package.json \
    dictionaries/dictionaries/nb/readme.md \
    dictionaries/dictionaries/nds/index.aff \
    dictionaries/dictionaries/nds/index.dic \
    dictionaries/dictionaries/nds/index.js \
    dictionaries/dictionaries/nds/license \
    dictionaries/dictionaries/nds/package.json \
    dictionaries/dictionaries/nds/readme.md \
    dictionaries/dictionaries/ne/index.aff \
    dictionaries/dictionaries/ne/index.dic \
    dictionaries/dictionaries/ne/index.js \
    dictionaries/dictionaries/ne/license \
    dictionaries/dictionaries/ne/package.json \
    dictionaries/dictionaries/ne/readme.md \
    dictionaries/dictionaries/nl/index.aff \
    dictionaries/dictionaries/nl/index.dic \
    dictionaries/dictionaries/nl/index.js \
    dictionaries/dictionaries/nl/license \
    dictionaries/dictionaries/nl/package.json \
    dictionaries/dictionaries/nl/readme.md \
    dictionaries/dictionaries/nn/index.aff \
    dictionaries/dictionaries/nn/index.dic \
    dictionaries/dictionaries/nn/index.js \
    dictionaries/dictionaries/nn/license \
    dictionaries/dictionaries/nn/package.json \
    dictionaries/dictionaries/nn/readme.md \
    dictionaries/dictionaries/oc/index.aff \
    dictionaries/dictionaries/oc/index.dic \
    dictionaries/dictionaries/oc/index.js \
    dictionaries/dictionaries/oc/licence \
    dictionaries/dictionaries/oc/license \
    dictionaries/dictionaries/oc/package.json \
    dictionaries/dictionaries/oc/readme.md \
    dictionaries/dictionaries/pl/index.aff \
    dictionaries/dictionaries/pl/index.dic \
    dictionaries/dictionaries/pl/index.js \
    dictionaries/dictionaries/pl/license \
    dictionaries/dictionaries/pl/package.json \
    dictionaries/dictionaries/pl/readme.md \
    dictionaries/dictionaries/pt-PT/index.aff \
    dictionaries/dictionaries/pt-PT/index.dic \
    dictionaries/dictionaries/pt-PT/index.js \
    dictionaries/dictionaries/pt-PT/license \
    dictionaries/dictionaries/pt-PT/package.json \
    dictionaries/dictionaries/pt-PT/readme.md \
    dictionaries/dictionaries/pt/index.aff \
    dictionaries/dictionaries/pt/index.dic \
    dictionaries/dictionaries/pt/index.js \
    dictionaries/dictionaries/pt/license \
    dictionaries/dictionaries/pt/package.json \
    dictionaries/dictionaries/pt/readme.md \
    dictionaries/dictionaries/ro/index.aff \
    dictionaries/dictionaries/ro/index.dic \
    dictionaries/dictionaries/ro/index.js \
    dictionaries/dictionaries/ro/license \
    dictionaries/dictionaries/ro/package.json \
    dictionaries/dictionaries/ro/readme.md \
    dictionaries/dictionaries/ru/index.aff \
    dictionaries/dictionaries/ru/index.dic \
    dictionaries/dictionaries/ru/index.js \
    dictionaries/dictionaries/ru/license \
    dictionaries/dictionaries/ru/package.json \
    dictionaries/dictionaries/ru/readme.md \
    dictionaries/dictionaries/rw/index.aff \
    dictionaries/dictionaries/rw/index.dic \
    dictionaries/dictionaries/rw/index.js \
    dictionaries/dictionaries/rw/license \
    dictionaries/dictionaries/rw/package.json \
    dictionaries/dictionaries/rw/readme.md \
    dictionaries/dictionaries/sk/index.aff \
    dictionaries/dictionaries/sk/index.dic \
    dictionaries/dictionaries/sk/index.js \
    dictionaries/dictionaries/sk/license \
    dictionaries/dictionaries/sk/package.json \
    dictionaries/dictionaries/sk/readme.md \
    dictionaries/dictionaries/sl/index.aff \
    dictionaries/dictionaries/sl/index.dic \
    dictionaries/dictionaries/sl/index.js \
    dictionaries/dictionaries/sl/license \
    dictionaries/dictionaries/sl/package.json \
    dictionaries/dictionaries/sl/readme.md \
    dictionaries/dictionaries/sr-Latn/index.aff \
    dictionaries/dictionaries/sr-Latn/index.dic \
    dictionaries/dictionaries/sr-Latn/index.js \
    dictionaries/dictionaries/sr-Latn/license \
    dictionaries/dictionaries/sr-Latn/package.json \
    dictionaries/dictionaries/sr-Latn/readme.md \
    dictionaries/dictionaries/sr/index.aff \
    dictionaries/dictionaries/sr/index.dic \
    dictionaries/dictionaries/sr/index.js \
    dictionaries/dictionaries/sr/license \
    dictionaries/dictionaries/sr/package.json \
    dictionaries/dictionaries/sr/readme.md \
    dictionaries/dictionaries/sv-FI/index.aff \
    dictionaries/dictionaries/sv-FI/index.dic \
    dictionaries/dictionaries/sv-FI/index.js \
    dictionaries/dictionaries/sv-FI/license \
    dictionaries/dictionaries/sv-FI/package.json \
    dictionaries/dictionaries/sv-FI/readme.md \
    dictionaries/dictionaries/sv/index.aff \
    dictionaries/dictionaries/sv/index.dic \
    dictionaries/dictionaries/sv/index.js \
    dictionaries/dictionaries/sv/license \
    dictionaries/dictionaries/sv/package.json \
    dictionaries/dictionaries/sv/readme.md \
    dictionaries/dictionaries/tk/index.aff \
    dictionaries/dictionaries/tk/index.dic \
    dictionaries/dictionaries/tk/index.js \
    dictionaries/dictionaries/tk/license \
    dictionaries/dictionaries/tk/package.json \
    dictionaries/dictionaries/tk/readme.md \
    dictionaries/dictionaries/tlh-Latn/index.aff \
    dictionaries/dictionaries/tlh-Latn/index.dic \
    dictionaries/dictionaries/tlh-Latn/index.js \
    dictionaries/dictionaries/tlh-Latn/license \
    dictionaries/dictionaries/tlh-Latn/package.json \
    dictionaries/dictionaries/tlh-Latn/readme.md \
    dictionaries/dictionaries/tlh/index.aff \
    dictionaries/dictionaries/tlh/index.dic \
    dictionaries/dictionaries/tlh/index.js \
    dictionaries/dictionaries/tlh/license \
    dictionaries/dictionaries/tlh/package.json \
    dictionaries/dictionaries/tlh/readme.md \
    dictionaries/dictionaries/tr/index.aff \
    dictionaries/dictionaries/tr/index.dic \
    dictionaries/dictionaries/tr/index.js \
    dictionaries/dictionaries/tr/license \
    dictionaries/dictionaries/tr/package.json \
    dictionaries/dictionaries/tr/readme.md \
    dictionaries/dictionaries/uk/index.aff \
    dictionaries/dictionaries/uk/index.dic \
    dictionaries/dictionaries/uk/index.js \
    dictionaries/dictionaries/uk/license \
    dictionaries/dictionaries/uk/package.json \
    dictionaries/dictionaries/uk/readme.md \
    dictionaries/dictionaries/vi/index.aff \
    dictionaries/dictionaries/vi/index.dic \
    dictionaries/dictionaries/vi/index.js \
    dictionaries/dictionaries/vi/license \
    dictionaries/dictionaries/vi/package.json \
    dictionaries/dictionaries/vi/readme.md \
    hunspell/src/hunspell/Makefile.am \
    light_style.qss

RESOURCES += \
    Editor.qrc

ICON = Icon.png
